language: node_js
node_js:
  - "7.1"
  - "6.9"
  - "4.6"
  - "stable"

install:
  - npm install
  - npm install --prefix ./examples/botkit-starter-slack
  - npm install --prefix ./examples/convo_bot

script:
  - npm run test_mocha
  - npm run test_jasmine
  - npm test --prefix ./examples/botkit-starter-slack
  - npm run test_mocha --prefix ./examples/convo_bot
  - npm run test_jasmine --prefix ./examples/convo_bot